#!/bin/bash
cd ~/Desktop
sed '/[Zz][Oo][Oo]/d' pandas.tsv > pandas_zoos.txt
awk '{print $1,$3,$2}' pandas_zoos.txt | sort -k 2 > sorted_pandas.txt
awk '{print $5}' pandas.tsv | sort -u > panda_zoos_a2z.txt
sed -e 's/male/M/g' -e 's/female/F/g' sorted_pandas.txt > panda_m_f.txt
echo "Female pandas born in October:"
grep -ic "female.*October" pandas.tsv
nl -bt pandas.tsv > panda_names.txt
sed -n -e '2p' -e '6p' -e '17p' panda_names.txt > lines_1_6_17.txt
grep -i "x" panda_names.txt > x_lines.txt
awk '{print $4}' pandas.tsv | sort | uniq > unique_places.txt
awk -F'\t' '{split($3,dob,"-"); age = strftime("%Y") - dob[1]; if (strftime("%m%d") < dob[2] dob[3]) age--; print $1, age}' pandas.tsv > pandas_age.txt
awk '$2 <= 10 {print $1,$2}' pandas_age.txt > young_pandas.txt
